admin_control/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$', views.manage),
	url(r'^courses/$', views.courses),	
	url(r'^programs/$', views.programs),	
	url(r'^add_course/$', views.add_course),	
	url(r'^add_program/$', views.add_program),	
	url(r'^edit_course/$', views.edit_course),	
	url(r'^edit_program/$', views.edit_program),	

	url(r'^assignments/$', views.assignments),	
	url(r'^add_assignment/$', views.add_assignment),

	url(r'^settings/$', views.settings),	
	url(r'^save_settings/$', views.save_settings),

	url(r'^users/$', views.users),	
	url(r'^add_user/$', views.add_user),	
]

core/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$', views.index),
	url(r'^logout/$', views.log_out),
	url(r'^signup/$', views.sign_up),
	url(r'^account/$', views.account),
	url(r'^manage/', include('admin_control.urls')),
	url(r'^projects/', include('repository.urls')),
	url(r'^community/', include('community.urls')),
]

thesismates/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from repository import views

urlpatterns = [
    url(r'', include('core.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'session_security/', include('session_security.urls')),
    url(r'^user/password/reset/$', 
            'django.contrib.auth.views.password_reset', 
            {'post_reset_redirect' : '/user/password/reset/done/'},
            name="password_reset"),
    url(r'^user/password/reset/done/$',
            'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
            'django.contrib.auth.views.password_reset_confirm', 
            {'post_reset_redirect' : '/user/password/done/'},
            name="password_reset_confirm"),
    url(r'^user/password/done/$', 
            'django.contrib.auth.views.password_reset_complete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_control/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User

# --------------------------------------------------------------------

class Program(models.Model):
	# Attributes
	code         = models.CharField(max_length=50, unique=True)
	name         = models.CharField(max_length=50, unique=True)
	description  = models.CharField(max_length=255)
	created_date = models.DateTimeField(default=timezone.now)

	# Methods
	def __unicode__(self):
	    return self.name

# --------------------------------------------------------------------

class Course(models.Model):
	# Attributes
	name         = models.CharField(max_length=255)
	created_date = models.DateTimeField(default=timezone.now)

	# Relations
	program = models.ForeignKey(Program, related_name='program')

	# Methods
	def __unicode__(self):
	    return self.name

	class Meta:
		ordering = ('name',)


# --------------------------------------------------------------------

class Setting(models.Model):
	# Attributes
	name  = models.CharField(max_length=50)
	value = models.CharField(max_length=50)

	# Methods
	def __unicode__(self):
		return self.value

# --------------------------------------------------------------------

class Course_Faculty_Assignment(models.Model):
	# Attributes
	semester   = models.CharField(max_length=50)
	start_sy   = models.CharField(max_length=50)
	end_sy     = models.CharField(max_length=50)
	assignment = models.CharField(max_length=255)

	# Relations
	course  = models.ForeignKey(Course, related_name="course")
	faculty = models.ForeignKey(User, related_name="faculty")

	# Methods
	def __unicode__(self):
		return self.course.name

# --------------------------------------------------------------------

admin.site.register(Course)
admin.site.register(Program)
admin.site.register(Setting)
admin.site.register(Course_Faculty_Assignment)

repository/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
from admin_control.models import Course, Course_Faculty_Assignment
import os
import uuid
from django.conf import settings
from django.dispatch import receiver

from PyPDF2 import PdfFileReader
from wand.image import Image

# --------------------------------------------------------------------

class Project(models.Model):
	# Attributes
    title          = models.CharField(max_length=200, unique=True)
    abstract       = models.TextField(max_length=200, blank=True, null=True)
    created_date   = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    secret_code    = models.CharField(max_length=50)
    slug           = models.TextField()
    uid            = models.UUIDField(default=uuid.uuid4, editable=False)
    status         = models.CharField(max_length=200, default="ongoing")

	# Relations
    members     = models.ManyToManyField(User, through='Project_Membership')
    coordinator = models.ForeignKey(
        Course_Faculty_Assignment, related_name="coordinator"
    )
    adviser = models.ForeignKey(
		Course_Faculty_Assignment, related_name="adviser",
		blank = True, null = True
	)

	# Methods
    def __unicode__(self):
        return self.title

# --------------------------------------------------------------------

class Project_Membership(models.Model):
	# Attributes
    added_date = models.DateTimeField(default=timezone.now)

	# Relations
    project = models.ForeignKey(Project, related_name='project')
    member  = models.ForeignKey(User, related_name='member')


	# Methods
    def __unicode__(self):
        return self.project.title

# --------------------------------------------------------------------

class Event(models.Model):
	# Attributes
    title      = models.CharField(max_length=50)
    start_date = models.DateField(null=True)
    end_date   = models.DateField(null=True)
    start_time = models.TimeField(blank=True, null=True)
    end_time   = models.TimeField(blank=True, null=True)
    event_type = models.CharField(max_length=50, null=True)
    notes      = models.TextField(null=True, blank=True)

	# Relations
    project_owner    = models.ForeignKey(Project, related_name='project_owner', blank=True, null=True)
    course_owner = models.ForeignKey(Course_Faculty_Assignment, related_name='course_owner', blank=True, null=True)
    posted_by        = models.ForeignKey(User, related_name='posted_by')
    included_members = models.ManyToManyField(User, through='Event_Actor')

	# Methods
    def __unicode__(self):
        return self.title

# --------------------------------------------------------------------

class Event_Actor(models.Model):
    # Relations
    event = models.ForeignKey(Event, related_name="event")
    member = models.ForeignKey(User, related_name="included_member")

    # Methods
    def __unicode__(self):
        return self.event.title

# --------------------------------------------------------------------

def generate_filename(self, filename):
    url = "docpriv/%s/%s" % (self.owner.id, filename)
    return url

# --------------------------------------------------------------------

class Document(models.Model):
	# Attributes
    docfile      = models.FileField(upload_to=generate_filename)
    mime_type    = models.CharField(max_length=255)
    official     = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)

    # Relations
    owner       = models.ForeignKey(Project, related_name='owner')
    uploaded_by = models.ForeignKey(User, related_name='uploaded_by')

    # Methods
    def filename(self):
        return os.path.basename(self.docfile.name)

    def __convert_to_img__(self, width, height, format='jpg'):
    	size = ''
        if width and height:
            size = '_' + str(width) + 'x' + str(height) + 'px'

        # FILE PATH
        filename = self.docfile.name
        filepath = settings.MEDIA_ROOT + '/' + filename
        
        output_dir = "%s/public/image_docs/%s/" % (settings.MEDIA_ROOT, self.owner.uid)

        os.mkdir(output_dir)

        input_file = PdfFileReader(file(filepath, 'rb'))

        for i in range(input_file.getNumPages()):
            with Image(filename = filepath + '[' + str(i) + ']', 
                resolution=100) as img:
                if len(size) > 0:
                    img.resize(width, height)

                img.format = format
                img.save(filename = output_dir + str(i) + '.' + format)

    def convert_to_png(self, width=0, height=0):
        self.__convert_to_img__(width, height, 'png')

    def convert_to_jpg(self, width=0, height=0):
        self.__convert_to_img__(width, height, 'jpg')

# --------------------------------------------------------------------

@receiver(models.signals.post_delete, sender=Document)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `Document` object is deleted.
    """
    if instance.docfile:
        if os.path.isfile(instance.docfile.path):
            os.remove(instance.docfile.path)

# --------------------------------------------------------------------

class Project_Log(models.Model):
    # Attributes
    message      = models.TextField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)
    semester   = models.CharField(max_length=50)
    start_sy   = models.CharField(max_length=50)
    end_sy     = models.CharField(max_length=50)

    # Relations
    project_log = models.ForeignKey(Project, related_name='project_log', null=True, blank=True)
    course_log = models.ForeignKey(Course_Faculty_Assignment, related_name='course_log', null = True, blank = True)
    actor   = models.ForeignKey(User, related_name='actor', null=True)

    # Methods
    def __unicode__(self):
        return self.message

# --------------------------------------------------------------------

class Project_Adviser_Request(models.Model):
    # Relations
    requester = models.ForeignKey(Project, related_name='requester')
    requested = models.ForeignKey(
        Course_Faculty_Assignment, related_name="requested",
    )
    accepted = models.NullBooleanField(null=True)

    def __unicode__(self):
        return self.requester.title

# --------------------------------------------------------------------

class User_Last_Visit_Ongoing(models.Model):
    # Attributes
    last_visit = models.DateTimeField(null=True)

    # Relations
    user = models.ForeignKey(User, related_name="user")

    def __unicode__(self):
        return str(self.last_visit)

# --------------------------------------------------------------------

class User_Docu_Request(models.Model):
    user = models.ForeignKey(User, related_name="docu_requester")
    req_docs = models.ForeignKey(Project, related_name='req_docs')
    semester   = models.CharField(max_length=50)
    start_sy   = models.CharField(max_length=50)
    end_sy     = models.CharField(max_length=50)
    access = models.NullBooleanField(null=False)

    def __unicode__(self):
        return str(self.user.username)

admin.site.register(Project)
admin.site.register(User_Docu_Request)
admin.site.register(Project_Membership)
admin.site.register(Event)
admin.site.register(Document)
admin.site.register(Project_Adviser_Request)

admin_control/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django_ajax.decorators import ajax
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseForbidden, JsonResponse
from django.contrib.auth.decorators import (
	user_passes_test
)

from . import models as adcon_m
from . import forms as adcon_f
from . import utils
from core import utils as core_u

# --------------------------------------------------------------------

def manage(request):
	if core_u.is_admin(request.user) == True:
		context = {}
		context['is_admin'] = True
		context['manage'] = True

		return render(request, 'admin_control/manage.html', context)
	else:
		return HttpResponseForbidden()

# --------------------------------------------------------------------

@ajax
def courses(request):
	context = {}

	courses_list = adcon_m.Course.objects.all()

	context['courses'] = courses_list
	context['form'] = adcon_f.CourseForm()

	return render(request, 'admin_control/partials/courses.html',context)

# --------------------------------------------------------------------

@ajax
def programs(request):
	context = {}
	context['form'] = adcon_f.ProgramForm()
	context['programs'] = adcon_m.Program.objects.all()

	return render(request, 'admin_control/partials/programs.html', context)

# --------------------------------------------------------------------

@ajax
def add_program(request):
	response = {}
	form = adcon_f.ProgramForm(request.POST)

	if form.is_valid():
		form.save()
		response['valid'] = True
	else:
		response['valid'] = False
		response['errors'] = form.errors

	return response

# --------------------------------------------------------------------

@ajax
def add_course(request):
	response = {}
	course_form = adcon_f.CourseForm(request.POST)

	if course_form.is_valid():
		object = course_form.save()
		response['code'] = object.program.code
		response['valid'] = True
	else:
		response['valid'] = False
		response['errors'] = course_form.errors

	return response

# --------------------------------------------------------------------

@ajax
def edit_program(request):
	orig = request.POST.get('originalName')
	name = request.POST.get('name')
	code = request.POST.get('code')
	desc = request.POST.get('desc')

	adcon_m.Program.objects.filter(name=orig).update(
		code = code,
		name = name,
		description = desc
	)

	print "PASOK"

# --------------------------------------------------------------------

@ajax
def edit_course(request):
	new_name = request.POST.get('newName')
	original_name = request.POST.get('originalName')

	edited = adcon_m.Course.objects.filter(name=original_name).update(name=new_name)

# --------------------------------------------------------------------

@ajax
def settings(request):
	context = {}
	admin_settings = adcon_m.Setting.objects.all()

	current_start_sy = admin_settings.get(name="start_school_year").value
	current_end_sy = admin_settings.get(name="end_school_year").value
	current_sem = admin_settings.get(name="semester").value
	current_capacity = admin_settings.get(
		name="working_files_capacity").value

	sy = "%s - %s" % (current_start_sy, current_end_sy)

	context['sem_form'] = adcon_f.SemForm(
			initial ={'value': current_sem},
			prefix = "sem-form"
		)
	context['sy_form'] = adcon_f.SyForm(
			initial ={'value': sy},
			prefix = "sy-form"
		)

	context['capacity_form'] = adcon_f.CapacityForm(
			initial={'value': current_capacity},
			prefix = "capacity-form"
		)

	return render(request,'admin_control/partials/settings.html',context)

# --------------------------------------------------------------------

@ajax
def save_settings(request):
	sem = request.POST.get('sem')
	sy = request.POST.get('sy')
	capacity = request.POST.get('capacity')

	sy = sy.replace('-', ' ').split(' ')

	sem_to_update = adcon_m.Setting.objects.filter(name="semester")
	sem_to_update.update(value=sem)

	start_sy_to_update = adcon_m.Setting.objects.filter(name="start_school_year")
	start_sy_to_update.update(value=sy[0])

	end_sy_to_update = adcon_m.Setting.objects.filter(name="end_school_year")
	end_sy_to_update.update(value=sy[1])

	capacity_to_update = adcon_m.Setting.objects.filter(name="working_files_capacity")
	capacity_to_update.update(value=capacity)

# --------------------------------------------------------------------

@ajax
def assignments(request):
	context = {}
	
	context['assignments'] = adcon_m.Course_Faculty_Assignment.objects.all()
	context['form'] = adcon_f.TermCourseForm()
	context['faculty'] = User.objects.filter(groups__name='faculty')

	return render(request,'admin_control/partials/assignments.html',context)

# --------------------------------------------------------------------

@ajax
def add_assignment(request):
	response = {}
	course = request.POST.get('course')
	coordinator = request.POST.get('faculty')
	add_assignment_form = adcon_f.TermCourseForm(request.POST)

	if add_assignment_form.is_valid():
		response = add_assignment_form.save_assignment(course, coordinator)
	else:
		response['valid'] = False
		response['errors'] = "Please fill up all the fields."

	return response

# --------------------------------------------------------------------

@ajax
def users(request):
	context = {}

	context['users'] = User.objects.exclude(username="master")
	context['form'] = adcon_f.AdminAddUserForm()

	return render(request, 'admin_control/partials/users.html', context)

# --------------------------------------------------------------------

@ajax
def add_user(request):
	email = request.POST.get('email')
	return utils.create_user_send_invite(email)

admin_control/templates/admin_control/partials/assignments.html
<div class="row">
	<div class="col-md-3">
		<strong>Add Assignment</strong>
		<form id="add-assignment-form" action="#" method="POST">
		{% csrf_token %}
			<div class="form-group">
				<label for="id_course">Course</label>
				{{ form.course }}
			</div>
			<div class="form-group">
				<label for="id_coordinator">Coordinator</label>
				<select name="coordinator" id="id_faculty" style="width: 100%" class="django-select2">
					{% for user in faculty %}
						<option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }} ({{ user.email }})</option>
					{% endfor %}
				</select>
			</div>

			<button class="btn btn-default" type="submit">Add</button>
			<p id="add-assignment-form-response" class="text-success"></p>
		</form>
	</div>
	<div class="col-md-9">
		<div>
			<table id="assignments-table" class="table table-condensed table-striped table-hover display">
				<thead>
					<tr>
						<th>Course</th>
						<th>User</th>
						<th>Assignment</th>
						<th>Semester</th>
						<th>School Year</th>
					</tr>
				</thead>
				<tbody>
					{% for assignment in assignments %}
						<tr>
							<td>{{ assignment.course }}</td>
							<td>{{ assignment.faculty.first_name }} {{ assignment.faculty.last_name }}</td>
							<td>{{ assignment.assignment | capfirst }}</td>
							<td>{{ assignment.semester }}</td>
							<td>{{ assignment.start_sy}} - {{ assignment.end_sy }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% load staticfiles %}
<script src="{% static 'admin_control/js/assignments.js' %}"></script>

admin_control/templates/admin_control/partials/courses.html
<div class="row">
	<div class="col-md-3">
		<strong>Add Course</strong>
		<form id="add-course-form" method="post" action="#">
		{% csrf_token %}
			<div class="form-group">
				{{ form.name }}
			</div>

			<div class="form-group">
				{{ form.program }}
			</div>

			<button class="btn btn-default" type="submit">Add</button>

			<p id="add-course-form-response"></p>
		</form>
		<hr>
		<strong>Edit Course</strong>
		<p>Select a row from the table to edit</p>
		<form id="edit-course-form" method="post" action="#">
		{% csrf_token %}
			<div class="form-group">
				{{ form.name }}
			</div>

			<button class="btn btn-default" type="submit">Submit</button>

			<p id="edit-course-form-response" class="text-success"></p>
		</form>
	</div>
	<div class="col-md-9">
		<table id="courses-table" class="table table-condensed table-striped table-hover display">
			<thead>
				<tr>
					<th>Course</th>
					<th>Program</th>
					<th>Created Date</th>
				</tr>
			</thead>
			<tbody>
				{% for course in courses %}
					<tr>
						<td>{{ course.name }}</td>
						<td>{{ course.program.code }}</td>
						<td>{{ course.created_date|date:"F d, o" }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% load staticfiles %}
<script src="{% static 'admin_control/js/courses.js' %}"></script>

admin_control/templates/admin_control/partials/programs.html
<div class="row">
	<div class="col-md-3">
		<strong>Add Program</strong>
		<form id="add-program-form" method="post" action="#">
		{% csrf_token %}
			<div class="form-group">
				{{ form.code }}
			</div>

			<div class="form-group">
				{{ form.name }}
			</div>

			<div class="form-group">
				{{ form.description }}
			</div>

			<button class="btn btn-default" type="submit">Add</button>

			<p id="add-program-form-response"></p>
		</form>
		<hr>
		<strong>Edit Program</strong>
		<p>Select a row from the table to edit</p>
		<form id="edit-program-form" method="post" action="#">
		{% csrf_token %}
			<div class="form-group">
				{{ form.code }}
			</div>

			<div class="form-group">
				{{ form.name }}
			</div>

			<div class="form-group">
				{{ form.description }}
			</div>

			<button class="btn btn-default" type="submit">Submit</button>

			<p id="add-program-form-response"></p>
		</form>
	</div>
	<div class="col-md-9">
		<table id="program-table" class="table table-condensed table-striped table-hover display">
			<thead>
				<tr>
					<th>Program Code</th>
					<th>Program Name</th>
					<th>Program Description</th>
					<th>Created Date</th>
				</tr>
			</thead>
			<tbody>
				{% for program in programs %}
					<tr>
						<td>{{ program.code }}</td>
						<td>{{ program.name }}</td>
						<td>{{ program.description }}</td>
						<td>{{ program.created_date|date:"F d, o" }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% load staticfiles %}
<script src="{% static 'admin_control/js/program.js' %}"></script>

admin_control/templates/admin_control/partials/settings.html
<div class="row">
	<div class="col-md-12">
		<form id="settings-form" action="#" method="POST">
			{% csrf_token %}
			<h3>School Year and Semester</h3>
			<div class="form-inline form-group">
				<label for="id_sy-form-value">School Year:</label>
				{{ sy_form.value }}
			</div>

			<div class="form-group form-inline">
				<label for="id_sem-form-value">Semester:</label>
				{{ sem_form.value }}
			</div>

			<h3>Projects</h3>
			<div class="form-group form-inline">
				<label for="id_capacity-form-value">Working files capacity:</label>
				{{ capacity_form.value }}
				<span>mb</span>
			</div>

			<p id="settings-form-response" class="text-success"></p>
			<button class="btn btn-default" type="submit">Submit</button
		</form>
	</div>
</div>

{% load staticfiles %}
<script src="{% static 'admin_control/js/settings.js' %}"></script>

admin_control/templates/admin_control/partials/users.html
<div class="row">
	<div class="col-md-3">
		<strong>Add Faculty</strong>
		<form id="add-user-form" method="post" action="#">
		{% csrf_token %}
			<div class="form-group">
				{{ form.email }}
			</div>

			<button class="btn btn-default" type="submit">Add</button>

			<p id="add-user-form-response"></p>
		</form>
	</div>
	<div class="col-md-9">
		<table id="users-table" class="table table-condensed table-striped table-hover display">
			<thead>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Email</th>
					<th>User Level</th>
					<th>Date Joined</th>
				</tr>
			</thead>
			<tbody>
				{% for user in users %}
					{% if user.last_login != None %}
						<tr>
							<td>{{ user.first_name }}</td>
							<td>{{ user.last_name }}</td>
							<td>{{ user.email }}</td>
							<td>{{ user.groups.all|first|capfirst }}</td>
							<td>{{ user.date_joined|date:"F d, o" }}</td>
						</tr>
					{% endif %}
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% load staticfiles %}
<script src="{% static 'admin_control/js/users.js' %}"></script>