community/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$', views.community),
	url(r'^ask_question/$', views.ask_question),	
	url(r'^accept/(?P<response>[-\w\d]+)/(?P<id>[-\w\d]+)$', views.accept),	
	url(r'^reject/(?P<response>[-\w\d]+)/(?P<id>[-\w\d]+)$', views.reject),	
	url(r'^search/$', views.get_search),	
	url(r'^(?P<id>[-\w\d]+)/(?P<slug>[-\w\d]+)/$', views.question),
	url(r'^(?P<id>[-\w\d]+)/(?P<slug>[-\w\d]+)/answer/$', views.answer),
]

core/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$', views.index),
	url(r'^logout/$', views.log_out),
	url(r'^signup/$', views.sign_up),
	url(r'^account/$', views.account),
	url(r'^manage/', include('admin_control.urls')),
	url(r'^projects/', include('repository.urls')),
	url(r'^community/', include('community.urls')),
]

thesismates/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from repository import views

urlpatterns = [
    url(r'', include('core.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'session_security/', include('session_security.urls')),
    url(r'^user/password/reset/$', 
            'django.contrib.auth.views.password_reset', 
            {'post_reset_redirect' : '/user/password/reset/done/'},
            name="password_reset"),
    url(r'^user/password/reset/done/$',
            'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
            'django.contrib.auth.views.password_reset_confirm', 
            {'post_reset_redirect' : '/user/password/done/'},
            name="password_reset_confirm"),
    url(r'^user/password/done/$', 
            'django.contrib.auth.views.password_reset_complete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User

# --------------------------------------------------------------------

class Question(models.Model):
	# Attributes
	title        = models.CharField(max_length=255, unique=True)
	description  = models.TextField(blank=True, null=True)
	created_date = models.DateTimeField(default=timezone.now)
	slug         = models.SlugField()
	accepted = models.NullBooleanField(null=True)

	# Relations
	asked_by = models.ForeignKey(User, related_name="asked_by")

	# Methods
	def __unicode__(self):
	    return self.title

# --------------------------------------------------------------------

class Question_Answer(models.Model):
	# Attributes
	answer       = models.TextField(blank=True, null=True)
	created_date = models.DateTimeField(default=timezone.now)
	accepted = models.NullBooleanField(null=True)

	# Relations
	question    = models.ForeignKey(Question, related_name="question")
	answered_by = models.ForeignKey(User, related_name="answered_by")

	# Methods
	def __unicode__(self):
	    return self.answer

# --------------------------------------------------------------------

admin.site.register(Question)
admin.site.register(Question_Answer)

community/forms.py
from django import forms
from . import models as com_m
from django.utils.text import slugify

# --------------------------------------------------------------------

class SearchForm(forms.Form):
    search = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class' : 'form-control',
                'type' : 'text',
                'placeholder' : 'Search keywords in question title'
                }
            )
        )

 # --------------------------------------------------------------------

class AskQuestionForm(forms.ModelForm):
	def save_question(self, user):
		title = self.cleaned_data['title']
		question = self.save(commit=False)
		question.asked_by = user
		question.slug = slugify(title)
		question.save()

		return question

	title = forms.CharField(
	    widget = forms.TextInput(
	        attrs = {
	            'class' : 'form-control'
	            }
	        )
	    )

	description = forms.CharField(
	        widget = forms.Textarea(
	            attrs = {
	                'class' : 'form-control',
	                'rows' : '3',
	            }
	        ),
	        required=False
	    )
	class Meta:
		model = com_m.Question
		fields = ('title','description')

# --------------------------------------------------------------------

class AnswerQuestionForm(forms.ModelForm):
	def save_answer(self, ques, user):
		answer = self.save(commit=False)
		answer.question = ques
		answer.answered_by = user
		answer.save()

	answer = forms.CharField(
	        widget = forms.Textarea(
	            attrs = {
	                'class' : 'form-control',
	                'rows' : '3',
	            }
	        ),
	    )
	class Meta:
		model = com_m.Question_Answer
		fields = ('answer',)

community/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import (
	login_required
)

from core import utils as core_u
from . import forms as com_f
from . import utils as com_u
from core import utils as core_u
from .models import Question, Question_Answer
from django_ajax.decorators import ajax
from django.http import HttpResponseForbidden

# --------------------------------------------------------------------

@login_required(redirect_field_name=None)
def community(request):
	context = {}
	context['questions'] = Question.objects.filter(accepted=True).order_by('-created_date')
	context['is_admin'] = core_u.is_admin(request.user)
	context['search_form'] = com_f.SearchForm()
	context['ask_form'] = com_f.AskQuestionForm()
	context['community'] = True

	if core_u.is_admin(request.user):
		pending_questions = Question.objects.filter(accepted=None)
		pending_answers = Question_Answer.objects.filter(accepted=None)
	else:
		pending_questions = Question.objects.filter(accepted=None,asked_by=request.user)
		pending_answers = Question_Answer.objects.filter(accepted=None, answered_by=request.user)


	if pending_questions:
		context['pending_qs'] = pending_questions.order_by('-created_date')

	if pending_answers:
		context['pending_as'] = pending_answers.order_by('-created_date')

	return render(request, 'community/community.html', context)

# --------------------------------------------------------------------

def question(request, id, slug):
	context = {}
	question = Question.objects.get(pk=id)
	if question.accepted == True:
		context['question'] = question
		context['answers'] = Question_Answer.objects.filter(
			question__pk=id, accepted=True).order_by('-created_date')
		context['answer_form'] = com_f.AnswerQuestionForm()
		context['community'] = True
		return render(request, 'community/question.html', context)
	else:
		return HttpResponseForbidden()


# --------------------------------------------------------------------

@ajax
def ask_question(request):
	form = com_f.AskQuestionForm(request.POST)

	if form.is_valid():
		question_object = form.save_question(request.user)
		return redirect(community)
	else:
		print "invalid"

# --------------------------------------------------------------------

def accept(request, response, id):
	if response == "question":
		q = Question.objects.filter(pk=id)
		q_obj = q.get()
		q.update(accepted=True)
		return redirect(question, q_obj.id, q_obj.slug)
	if response == "answer":
		a = Question_Answer.objects.filter(pk=id)
		a_obj = a.get()
		a.update(accepted=True)
		return redirect(question, a_obj.question.id, a_obj.question.slug)

# --------------------------------------------------------------------

def reject(request, response, id):
	if response == "question":
		q = Question.objects.filter(pk=id)
		q.delete()
		return redirect(community)
	if response == "answer":
		a = Question_Answer.objects.filter(pk=id)
		a.delete()
		return redirect(community)

# --------------------------------------------------------------------

@ajax
def get_search(request):
	form = com_f.SearchForm(request.POST)
	context = {}
	if form.is_valid():
		context['questions'] = com_u.get_search(form).order_by('-created_date')
		words = request.POST.get('search')
		keywords = words.split()
		context['keywords'] = keywords

		return render(request, 'community/search.html', context)

# --------------------------------------------------------------------

@ajax
def answer(request, id, slug):
	form = com_f.AnswerQuestionForm(request.POST)

	if form.is_valid():
		question_object = Question.objects.get(pk=id, slug=slug)
		form.save_answer(question_object, request.user)
		return redirect(question, id, slug)
	else:
		print "invalid"

community/templates/community/modals/ask_question_modal.html
{% extends "modal.html" %}

{% block modalID %}ask-question-modal{% endblock modalID %}

{% block modalTitle %}
	Ask a question
{% endblock modalTitle %}


{% block modalBody %}
	<div class="row">
		<div class="col-md-12">
			<form id="ask-question-form" action="#" method="POST">
			{% csrf_token %}
				<div class="form-group">
					<label for="id_title">Question</label>
					{{ ask_form.title }}
				</div>

				<div class="form-group">
					<label for="id_description">Details</label>
					{{ ask_form.description }}
				</div>

				<button class="btn btn-default" type="submit">Ask away</button>
				<p id="ask-question-form-response" class="text-success"></p>
			</form>
		</div>
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

community/templates/community/modals/pending_a.html
{% extends "modal.html" %}

{% block modalID %}pending-a-modal{% endblock modalID %}

{% block modalTitle %}
	Pending Answers
{% endblock modalTitle %}



{% block modalBody %}
	<div class="row">
		{% for answer in pending_as %}
			<div class="col-md-12 request">
				<h4>{{ answer.question.title }}</h4>
				<p>{{ answer.answer }}</p>
				{% if is_admin %}
					<a role="button" href="{% url 'community.views.accept' 'answer' answer.id %}" id="send-confirmation" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Accept</a>
					<a role="button" href="{% url 'community.views.reject' 'answer' answer.id %}" class="btn btn-danger btn-sm close-notif"><i class="fa fa-times-circle"></i> Reject</a>
				{% endif %}
				{% if not forloop.last %}
					<hr align="left">
				{% endif %}
			</div>
		{% endfor %}
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

community/templates/community/modals/pending_q.html
{% extends "modal.html" %}

{% block modalID %}pending-q-modal{% endblock modalID %}

{% block modalTitle %}
	Pending Questions
{% endblock modalTitle %}



{% block modalBody %}
	<div class="row">
		{% for question in pending_qs %}
			<div class="col-md-12 request">
				<h4>{{ question.title }}</h4>
				<p>{{ question.description }}</p>
				{% if is_admin %}
					<a role="button" href="{% url 'community.views.accept' 'question' question.id %}" id="send-confirmation" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Accept</a>
					<a role="button" href="{% url 'community.views.reject' 'question' question.id %}" class="btn btn-danger btn-sm close-notif"><i class="fa fa-times-circle"></i> Reject</a>
				{% endif %}
				{% if not forloop.last %}
					<hr align="left">
				{% endif %}
			</div>
		{% endfor %}
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}