core/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$', views.index),
	url(r'^logout/$', views.log_out),
	url(r'^signup/$', views.sign_up),
	url(r'^account/$', views.account),
	url(r'^manage/', include('admin_control.urls')),
	url(r'^projects/', include('repository.urls')),
	url(r'^community/', include('community.urls')),
]

repository/urls.py
from django.conf.urls import include, url
from . import views



urlpatterns = [
	# Get projects : project_status = "ongoing", "unpublished"
	url(r'^(?P<project_status>[-\w\d]+)/$', views.projects),
	url(r'^(?P<project_status>[-\w\d]+)/search/$', views.get_search),

	# Project Profile
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/$', views.project_profile),
	url(r'^(?P<project_status>[-\w\d]+)/generate_report/$', views.generate_report),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/profile$', views.profile),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/calendar$', views.calendar),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/files$', views.files),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/log$', views.log),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/get_user_for_delete$', views.get_user_for_delete),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/leave_group$', views.leave_group),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/request_adviser/$', views.request_adviser),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/(?P<response>[-\w\d]+)/respond_advisoree_request/$', views.respond_advisoree_request),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/documentation$', views.view_documentation),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/start_publication$', views.start_publication),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/start_confirmation/$', views.start_confirmation),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/start_processing/$', views.start_processing),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/rejection/$', views.rejection),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/edit_abstract/$', views.edit_abstract),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/edit_title/$', views.edit_title),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/doc_req/$', views.doc_req),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/get_event_instance/$', views.get_event_instance),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/save_manual/$', views.save_manual),

	# Specific Project controls
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/files$', views.files),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/add_member/$', views.add_member),

	# Calendar 
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/get_events/$', views.get_events),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/add_event/$', views.add_event),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/save_event_changes/$', views.save_event_changes),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/remove_event/$', views.remove_event),

	# Files
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/upload_file/$', views.upload_file),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/delete_file/(?P<fileid>[-\w\d]+)$', views.delete_file),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/download/(?P<fileid>[-\w\d]+)$', views.download_file),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/view/(?P<fileid>[-\w\d]+)$', views.view_file),

	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/journal$', views.generate_journal),

	# Global Project controls
	url(r'^(?P<project_status>[-\w\d]+)/add_project/$', views.add_project),
	url(r'^(?P<project_status>[-\w\d]+)/add_event/$', views.add_event),
	url(r'^(?P<project_status>[-\w\d]+)/assign_advisers/$', views.assign_advisers),
] 

thesismates/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from repository import views

urlpatterns = [
    url(r'', include('core.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'session_security/', include('session_security.urls')),
    url(r'^user/password/reset/$', 
            'django.contrib.auth.views.password_reset', 
            {'post_reset_redirect' : '/user/password/reset/done/'},
            name="password_reset"),
    url(r'^user/password/reset/done/$',
            'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
            'django.contrib.auth.views.password_reset_confirm', 
            {'post_reset_redirect' : '/user/password/done/'},
            name="password_reset_confirm"),
    url(r'^user/password/done/$', 
            'django.contrib.auth.views.password_reset_complete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_control/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User

# --------------------------------------------------------------------

class Program(models.Model):
	# Attributes
	code         = models.CharField(max_length=50, unique=True)
	name         = models.CharField(max_length=50, unique=True)
	description  = models.CharField(max_length=255)
	created_date = models.DateTimeField(default=timezone.now)

	# Methods
	def __unicode__(self):
	    return self.name

# --------------------------------------------------------------------

class Course(models.Model):
	# Attributes
	name         = models.CharField(max_length=255)
	created_date = models.DateTimeField(default=timezone.now)

	# Relations
	program = models.ForeignKey(Program, related_name='program')

	# Methods
	def __unicode__(self):
	    return self.name

	class Meta:
		ordering = ('name',)


# --------------------------------------------------------------------

class Setting(models.Model):
	# Attributes
	name  = models.CharField(max_length=50)
	value = models.CharField(max_length=50)

	# Methods
	def __unicode__(self):
		return self.value

# --------------------------------------------------------------------

class Course_Faculty_Assignment(models.Model):
	# Attributes
	semester   = models.CharField(max_length=50)
	start_sy   = models.CharField(max_length=50)
	end_sy     = models.CharField(max_length=50)
	assignment = models.CharField(max_length=255)

	# Relations
	course  = models.ForeignKey(Course, related_name="course")
	faculty = models.ForeignKey(User, related_name="faculty")

	# Methods
	def __unicode__(self):
		return self.course.name

# --------------------------------------------------------------------

admin.site.register(Course)
admin.site.register(Program)
admin.site.register(Setting)
admin.site.register(Course_Faculty_Assignment)

repository/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
from admin_control.models import Course, Course_Faculty_Assignment
import os
import uuid
from django.conf import settings
from django.dispatch import receiver

from PyPDF2 import PdfFileReader
from wand.image import Image

# --------------------------------------------------------------------

class Project(models.Model):
	# Attributes
    title          = models.CharField(max_length=200, unique=True)
    abstract       = models.TextField(max_length=200, blank=True, null=True)
    created_date   = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    secret_code    = models.CharField(max_length=50)
    slug           = models.TextField()
    uid            = models.UUIDField(default=uuid.uuid4, editable=False)
    status         = models.CharField(max_length=200, default="ongoing")

	# Relations
    members     = models.ManyToManyField(User, through='Project_Membership')
    coordinator = models.ForeignKey(
        Course_Faculty_Assignment, related_name="coordinator"
    )
    adviser = models.ForeignKey(
		Course_Faculty_Assignment, related_name="adviser",
		blank = True, null = True
	)

	# Methods
    def __unicode__(self):
        return self.title

# --------------------------------------------------------------------

class Project_Membership(models.Model):
	# Attributes
    added_date = models.DateTimeField(default=timezone.now)

	# Relations
    project = models.ForeignKey(Project, related_name='project')
    member  = models.ForeignKey(User, related_name='member')


	# Methods
    def __unicode__(self):
        return self.project.title

# --------------------------------------------------------------------

class Event(models.Model):
	# Attributes
    title      = models.CharField(max_length=50)
    start_date = models.DateField(null=True)
    end_date   = models.DateField(null=True)
    start_time = models.TimeField(blank=True, null=True)
    end_time   = models.TimeField(blank=True, null=True)
    event_type = models.CharField(max_length=50, null=True)
    notes      = models.TextField(null=True, blank=True)

	# Relations
    project_owner    = models.ForeignKey(Project, related_name='project_owner', blank=True, null=True)
    course_owner = models.ForeignKey(Course_Faculty_Assignment, related_name='course_owner', blank=True, null=True)
    posted_by        = models.ForeignKey(User, related_name='posted_by')
    included_members = models.ManyToManyField(User, through='Event_Actor')

	# Methods
    def __unicode__(self):
        return self.title

# --------------------------------------------------------------------

class Event_Actor(models.Model):
    # Relations
    event = models.ForeignKey(Event, related_name="event")
    member = models.ForeignKey(User, related_name="included_member")

    # Methods
    def __unicode__(self):
        return self.event.title

# --------------------------------------------------------------------

def generate_filename(self, filename):
    url = "docpriv/%s/%s" % (self.owner.id, filename)
    return url

# --------------------------------------------------------------------

class Document(models.Model):
	# Attributes
    docfile      = models.FileField(upload_to=generate_filename)
    mime_type    = models.CharField(max_length=255)
    official     = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)

    # Relations
    owner       = models.ForeignKey(Project, related_name='owner')
    uploaded_by = models.ForeignKey(User, related_name='uploaded_by')

    # Methods
    def filename(self):
        return os.path.basename(self.docfile.name)

    def __convert_to_img__(self, width, height, format='jpg'):
    	size = ''
        if width and height:
            size = '_' + str(width) + 'x' + str(height) + 'px'

        # FILE PATH
        filename = self.docfile.name
        filepath = settings.MEDIA_ROOT + '/' + filename
        
        output_dir = "%s/public/image_docs/%s/" % (settings.MEDIA_ROOT, self.owner.uid)

        os.mkdir(output_dir)

        input_file = PdfFileReader(file(filepath, 'rb'))

        for i in range(input_file.getNumPages()):
            with Image(filename = filepath + '[' + str(i) + ']', 
                resolution=100) as img:
                if len(size) > 0:
                    img.resize(width, height)

                img.format = format
                img.save(filename = output_dir + str(i) + '.' + format)

    def convert_to_png(self, width=0, height=0):
        self.__convert_to_img__(width, height, 'png')

    def convert_to_jpg(self, width=0, height=0):
        self.__convert_to_img__(width, height, 'jpg')

# --------------------------------------------------------------------

@receiver(models.signals.post_delete, sender=Document)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `Document` object is deleted.
    """
    if instance.docfile:
        if os.path.isfile(instance.docfile.path):
            os.remove(instance.docfile.path)

# --------------------------------------------------------------------

class Project_Log(models.Model):
    # Attributes
    message      = models.TextField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)
    semester   = models.CharField(max_length=50)
    start_sy   = models.CharField(max_length=50)
    end_sy     = models.CharField(max_length=50)

    # Relations
    project_log = models.ForeignKey(Project, related_name='project_log', null=True, blank=True)
    course_log = models.ForeignKey(Course_Faculty_Assignment, related_name='course_log', null = True, blank = True)
    actor   = models.ForeignKey(User, related_name='actor', null=True)

    # Methods
    def __unicode__(self):
        return self.message

# --------------------------------------------------------------------

class Project_Adviser_Request(models.Model):
    # Relations
    requester = models.ForeignKey(Project, related_name='requester')
    requested = models.ForeignKey(
        Course_Faculty_Assignment, related_name="requested",
    )
    accepted = models.NullBooleanField(null=True)

    def __unicode__(self):
        return self.requester.title

# --------------------------------------------------------------------

class User_Last_Visit_Ongoing(models.Model):
    # Attributes
    last_visit = models.DateTimeField(null=True)

    # Relations
    user = models.ForeignKey(User, related_name="user")

    def __unicode__(self):
        return str(self.last_visit)

# --------------------------------------------------------------------

class User_Docu_Request(models.Model):
    user = models.ForeignKey(User, related_name="docu_requester")
    req_docs = models.ForeignKey(Project, related_name='req_docs')
    semester   = models.CharField(max_length=50)
    start_sy   = models.CharField(max_length=50)
    end_sy     = models.CharField(max_length=50)
    access = models.NullBooleanField(null=False)

    def __unicode__(self):
        return str(self.user.username)

admin.site.register(Project)
admin.site.register(User_Docu_Request)
admin.site.register(Project_Membership)
admin.site.register(Event)
admin.site.register(Document)
admin.site.register(Project_Adviser_Request)

repository/templates/repository/modals/add_event_modal.html
{% extends "modal.html" %}

{% block modalID %}add-event-modal{% endblock modalID %}

{% block modalTitle %}
	Add Event
{% endblock modalTitle %}

{% block modalBody %}
	<div>
		<!-- Nav tabs -->
		<ul class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active"><a href="#deadline" aria-controls="deadline" role="tab" data-toggle="tab">Deadline</a></li>
			{% if is_member %}
			<li role="presentation"><a href="#journal" aria-controls="journal" role="tab" data-toggle="tab">Journal</a></li>
			{% endif %}
		</ul>

		<!-- Tab panes -->
		<form id="add-event-form" method="post" action="#">
		{% if not in_profile %}
			{% if is_admin or is_coor %}
				<br>
				<div class="form-group">
					<label for="id_title">Course for:</label>
					<select name="course" id="course" style="width: 100%" class="django-select2">
						{% for course in courses %}
							<option value="{{ course.id }}">{{ course.course.name }}</option>
						{% endfor %}
					</select>
				</div>
			{% endif %}
		{% endif %}
		{% csrf_token %}
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="deadline">
					<br>
					<div class="form-group">
						<label for="id_title">Deadline for:</label>
						{{ add_deadline_event_form.title }}
					</div>

					<div class="form-group">
						<label for="id_start">Deadline:</label>
						<div id="deadline-date-picker" class='input-group date datepicker'>
				            {{ add_deadline_event_form.start_date }}
				            <span class="input-group-addon">
				                <span class="glyphicon glyphicon-calendar"></span>
				            </span>

				        </div>
					</div>

					<div class="form-group">
						<div class='input-group date timepicker'>
				            {{ add_deadline_event_form.start_time }}
				            <span class="input-group-addon">
				                <span class="glyphicon glyphicon-time"></span>
				            </span>
				        </div>
					</div>

					<div class="form-group">
						<label for="id_notes">Notes:</label>
                        {{ add_deadline_event_form.notes }}
					</div>
				</div>

				<div role="tabpanel" class="tab-pane" id="journal">
					<br>
					<div class="form-group">
						<label for="id_title">Description of Activity:</label>
						{{ add_journal_event_form.title }}
					</div>

					<div class="form-group">
						<label for="id_start">Date:</label>
						<div id="journal-start-date-picker" class='input-group date datepicker'>
		                    {{ add_journal_event_form.start_date }}
		                    <span class="input-group-addon">
		                        <span class="glyphicon glyphicon-calendar"></span>
		                    </span>
		                </div>
					</div>

					<div class="form-group">	
						<label for="id_start">Included Members:</label>
						{% for member in members %}
							<div class="checkbox">
					         <label>
					           <input value="{{ member.id }}" class="included-members" type="checkbox" checked>
					           <span class="cr"><i class="fa fa-check cr-icon"></i></span>
					           {{ member.first_name }} {{ member.last_name }}
					         </label>
					       </div>
						{% endfor %}
					</div>

					<div class="form-group">
						<label for="id_notes">Results:</label>
                        {{ add_journal_event_form.notes }}
					</div>
				</div>
			</div>

			<div class="form-group text-right">
			    <button type="submit" class="btn btn-primary">Add</button>
			</div>

			<p id="add-event-form-response" class="text-success"></p>
		</form>
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/add_member_modal.html
{% extends "modal.html" %}

{% block modalID %}add-member-modal{% endblock modalID %}

{% block modalSize %}
	modal-sm
{% endblock modalSize %}

{% block modalTitle %}
	Add new member
{% endblock modalTitle %}

{% block modalBody %}
	<form id="add-member-form" method="post" action="#">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label for="id_user">Users: </label>
					<select name="user" id="id_user" style="width: 100%" class="django-select2">
						{% for user in non_members %}
							<option value="{{ user.id }}">{{ user.username }}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group text-right">
				    <button id="next" type="submit" class="btn btn-primary">Add</button>
				</div>

				<p id="add-member-form-response" class="text-success"></p>
			</div>
	    </div>
	</form>	
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/add_project_modal.html
{% extends "modal.html" %}

{% block modalID %}add-project-modal{% endblock modalID %}

{% block modalTitle %}
	Add new project
{% endblock modalTitle %}

{% block modalBody %}
	<form id="add-project-form" method="post" action="#">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label for="id_title">Project Title: </label>
					{{ add_project_form.title }}
				</div>

				<div class="form-group">
					<label for="id_title">Course: </label>
					<select name="coordinator" id="id_coordinator" style="width: 100%" class="django-select2 form-control">
						{% for course in courses %}
							<option value="{{ course.id }}">{{ course.course.name }}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group">
					<label for="id_user">Add Member: </label>
					{{ add_member_form.user }}
				</div>

				<div class="form-group text-right">
				    <button id="next" type="submit" class="btn btn-primary">Add</button>
				</div>

				<p id="add-project-form-response" class="text-success"></p>
			</div>
	    </div>
	</form>	
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/available_advisers_modal.html
{% extends "modal.html" %}

{% block modalID %}assign-available-advisers-modal{% endblock modalID %}

{% block modalTitle %}
	Assign available advisers
{% endblock modalTitle %}

{% block modalSize %}
	modal-lg
{% endblock modalSize %}

{% block modalBody %}
	<div class="row">
		<div class="col-md-9">
			<table id="available-advisers-table" class="table table-condensed table-striped table-hover display">
				<thead>
					<tr>
						<th>Course</th>
						<th>Faculty</th>
						<th>Project</th>
					</tr>
				</thead>
				<tbody>
					{% for assignment in available_advisers %}
						<tr>
							<td>{{ assignment.course }}</td>
							<td>{{ assignment.faculty.first_name }} {{ assignment.faculty.last_name }}</td>
							<td>None</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-md-3">
			<form id="aaa-form" action="#" method="POST">
			{% csrf_token %}
				<div class="form-group">
					<label for="id_title">Course: </label>
					<select name="coordinator" id="id_coordinator" style="width: 100%" class="django-select2">
						{% for course in courses %}
							<option value="{{ course.course.id }}">{{ course.course.name }}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group">
					<label for="id_faculty">Faculty</label>
					<select name="coordinator" id="id_faculty" style="width: 100%" class="django-select2">
						{% for user in faculty %}
							<option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }} ({{ user.email }})</option>
						{% endfor %}
					</select>
				</div>

				<button class="btn btn-default" type="submit">Add</button>
				<p id="aaa-form-response" class="text-success"></p>
			</form>

		</div>
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/edit_event_modal.html
{% extends "modal.html" %}

{% block modalID %}edit-event-modal{% endblock modalID %}

{% block modalTitle %}
	Edit Event
{% endblock modalTitle %}

{% block modalBody %}
	<div id="edit-form-container">
		<!-- Tab panes -->
		
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/event_details_modal.html
{% extends "modal.html" %}

{% block modalID %}event-details-modal{% endblock modalID %}

{% block modalSize %}
	modal-sm
{% endblock modalSize %}

{% block modalTitle %}
	<div id="modalTitle"></div>
{% endblock modalTitle %}

{% block modalBody %}
	<div id="modalBody">
		<div id="eventNotes"></div>
		<div>
			<br>
			<span><strong>Type:</strong></span>
			<div id="type"></div>
			<div id="includedMembers"></div>
			<br>
			<span><strong>Posted By:</strong></span>
			<br>
			<span id="postedBy"></span>
		</div>
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/program_modal.html
{% extends "modal.html" %}

{% block modalID %}program-modal{% endblock modalID %}

{% block modalTitle %}
	Generate thesis report
{% endblock modalTitle %}

{% block modalBody %}
	<form id="generate-report-form" method="post" action="{% url 'repository.views.generate_report' project_status %}">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label for="id_title">Choose program: </label>
					<select name="program" id="program" style="width: 100%" class="django-select2 form-control">
						<option value="all">All</option>
						{% for program in programs %}
							<option value="{{ program.id }}">{{ program.name }}</option>
						{% endfor %}
					</select>
				</div>

				<div class="form-group text-right">
				    <button id="next" type="submit" class="btn btn-primary">Generate</button>
				</div>
			</div>
	    </div>
	</form>	
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/request_adviser_modal.html
{% extends "modal.html" %}

{% block modalID %}request-adviser-modal{% endblock modalID %}

{% block modalSize %}
	modal-sm
{% endblock modalSize %}

{% block modalTitle %}
	Request Adviser
{% endblock modalTitle %}

{% block modalBody %}
	{% if has_request %}
		<div class="row">
			<div class="col-md-12 text-center">
				<p class="text-info">Your project has already sent an adviser request to <strong>{{ requested }}</strong>. Please wait for the response before requesting for another.</p>
			</div>
		</div>
	{% else %}
		<form id="request-adviser-form" method="post" action="#">
		{% csrf_token %}
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<label for="id_title">Choose from available Advisers: </label>
						<select name="faculty" id="faculty" style="width: 100%" class="django-select2 form-control">
							{% for assignment in available_advisers %}
								<option value="{{ assignment.id }}">{{ assignment.faculty.first_name }} {{ assignment.faculty.last_name }}</option>
							{% endfor %}
						</select>
					</div>

					<div class="form-group text-right">
					    <button id="next" type="submit" class="btn btn-primary">Send Request</button>
					</div>

					<p id="request-adviser-form-response" class="text-success"></p>
				</div>
		    </div>
		</form>	
	{% endif %}
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}

repository/templates/repository/modals/requests_modal.html
{% extends "modal.html" %}

{% block modalID %}requests-modal{% endblock modalID %}

{% block modalTitle %}
	Requests
{% endblock modalTitle %}



{% block modalBody %}
	<div class="row">
		{% for request in advisoree_requests %}
			<div class="col-md-12 request">
				<h4>Advisoree Request</h4>
				<p><strong>Project: </strong>{{ request.requester }}</p>
				<p><strong>Abstract: </strong>{{ request.requester.abstract }}</p>
				<a role="button" href="{% url 'repository.views.respond_advisoree_request' project_status request.requester.uid request.requester.slug "accepted" %}" id="send-confirmation" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Accept</a>
				<a role="button" href="{% url 'repository.views.respond_advisoree_request' project_status request.requester.uid request.requester.slug "rejected" %}"  class="btn btn-danger btn-sm close-notif"><i class="fa fa-times-circle"></i> Reject</a>
			</div>
		{% endfor %}
	</div>
{% endblock modalBody %}

{% block modalFooter %}
{% endblock modalFooter %}