core/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$', views.index),
	url(r'^logout/$', views.log_out),
	url(r'^signup/$', views.sign_up),
	url(r'^account/$', views.account),
	url(r'^manage/', include('admin_control.urls')),
	url(r'^projects/', include('repository.urls')),
	url(r'^community/', include('community.urls')),
]

repository/urls.py
from django.conf.urls import include, url
from . import views



urlpatterns = [
	# Get projects : project_status = "ongoing", "unpublished"
	url(r'^(?P<project_status>[-\w\d]+)/$', views.projects),
	url(r'^(?P<project_status>[-\w\d]+)/search/$', views.get_search),

	# Project Profile
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/$', views.project_profile),
	url(r'^(?P<project_status>[-\w\d]+)/generate_report/$', views.generate_report),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/profile$', views.profile),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/calendar$', views.calendar),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/files$', views.files),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/log$', views.log),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/get_user_for_delete$', views.get_user_for_delete),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/leave_group$', views.leave_group),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/request_adviser/$', views.request_adviser),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/(?P<response>[-\w\d]+)/respond_advisoree_request/$', views.respond_advisoree_request),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/documentation$', views.view_documentation),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/start_publication$', views.start_publication),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/start_confirmation/$', views.start_confirmation),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/start_processing/$', views.start_processing),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/rejection/$', views.rejection),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/edit_abstract/$', views.edit_abstract),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/edit_title/$', views.edit_title),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/doc_req/$', views.doc_req),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/get_event_instance/$', views.get_event_instance),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/save_manual/$', views.save_manual),

	# Specific Project controls
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/files$', views.files),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/add_member/$', views.add_member),

	# Calendar 
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/get_events/$', views.get_events),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/add_event/$', views.add_event),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/save_event_changes/$', views.save_event_changes),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/remove_event/$', views.remove_event),

	# Files
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/upload_file/$', views.upload_file),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/delete_file/(?P<fileid>[-\w\d]+)$', views.delete_file),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/download/(?P<fileid>[-\w\d]+)$', views.download_file),
	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/view/(?P<fileid>[-\w\d]+)$', views.view_file),

	url(r'^(?P<project_status>[-\w\d]+)/(?P<uid>[-\w\d]+)/(?P<slug>[-\w\d]+)/journal$', views.generate_journal),

	# Global Project controls
	url(r'^(?P<project_status>[-\w\d]+)/add_project/$', views.add_project),
	url(r'^(?P<project_status>[-\w\d]+)/add_event/$', views.add_event),
	url(r'^(?P<project_status>[-\w\d]+)/assign_advisers/$', views.assign_advisers),
] 

thesismates/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from repository import views

urlpatterns = [
    url(r'', include('core.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'session_security/', include('session_security.urls')),
    url(r'^user/password/reset/$', 
            'django.contrib.auth.views.password_reset', 
            {'post_reset_redirect' : '/user/password/reset/done/'},
            name="password_reset"),
    url(r'^user/password/reset/done/$',
            'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 
            'django.contrib.auth.views.password_reset_confirm', 
            {'post_reset_redirect' : '/user/password/done/'},
            name="password_reset_confirm"),
    url(r'^user/password/done/$', 
            'django.contrib.auth.views.password_reset_complete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repository/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
from admin_control.models import Course, Course_Faculty_Assignment
import os
import uuid
from django.conf import settings
from django.dispatch import receiver

from PyPDF2 import PdfFileReader
from wand.image import Image

# --------------------------------------------------------------------

class Project(models.Model):
	# Attributes
    title          = models.CharField(max_length=200, unique=True)
    abstract       = models.TextField(max_length=200, blank=True, null=True)
    created_date   = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    secret_code    = models.CharField(max_length=50)
    slug           = models.TextField()
    uid            = models.UUIDField(default=uuid.uuid4, editable=False)
    status         = models.CharField(max_length=200, default="ongoing")

	# Relations
    members     = models.ManyToManyField(User, through='Project_Membership')
    coordinator = models.ForeignKey(
        Course_Faculty_Assignment, related_name="coordinator"
    )
    adviser = models.ForeignKey(
		Course_Faculty_Assignment, related_name="adviser",
		blank = True, null = True
	)

	# Methods
    def __unicode__(self):
        return self.title

# --------------------------------------------------------------------

class Project_Membership(models.Model):
	# Attributes
    added_date = models.DateTimeField(default=timezone.now)

	# Relations
    project = models.ForeignKey(Project, related_name='project')
    member  = models.ForeignKey(User, related_name='member')


	# Methods
    def __unicode__(self):
        return self.project.title

# --------------------------------------------------------------------

class Event(models.Model):
	# Attributes
    title      = models.CharField(max_length=50)
    start_date = models.DateField(null=True)
    end_date   = models.DateField(null=True)
    start_time = models.TimeField(blank=True, null=True)
    end_time   = models.TimeField(blank=True, null=True)
    event_type = models.CharField(max_length=50, null=True)
    notes      = models.TextField(null=True, blank=True)

	# Relations
    project_owner    = models.ForeignKey(Project, related_name='project_owner', blank=True, null=True)
    course_owner = models.ForeignKey(Course_Faculty_Assignment, related_name='course_owner', blank=True, null=True)
    posted_by        = models.ForeignKey(User, related_name='posted_by')
    included_members = models.ManyToManyField(User, through='Event_Actor')

	# Methods
    def __unicode__(self):
        return self.title

# --------------------------------------------------------------------

class Event_Actor(models.Model):
    # Relations
    event = models.ForeignKey(Event, related_name="event")
    member = models.ForeignKey(User, related_name="included_member")

    # Methods
    def __unicode__(self):
        return self.event.title

# --------------------------------------------------------------------

def generate_filename(self, filename):
    url = "docpriv/%s/%s" % (self.owner.id, filename)
    return url

# --------------------------------------------------------------------

class Document(models.Model):
	# Attributes
    docfile      = models.FileField(upload_to=generate_filename)
    mime_type    = models.CharField(max_length=255)
    official     = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)

    # Relations
    owner       = models.ForeignKey(Project, related_name='owner')
    uploaded_by = models.ForeignKey(User, related_name='uploaded_by')

    # Methods
    def filename(self):
        return os.path.basename(self.docfile.name)

    def __convert_to_img__(self, width, height, format='jpg'):
    	size = ''
        if width and height:
            size = '_' + str(width) + 'x' + str(height) + 'px'

        # FILE PATH
        filename = self.docfile.name
        filepath = settings.MEDIA_ROOT + '/' + filename
        
        output_dir = "%s/public/image_docs/%s/" % (settings.MEDIA_ROOT, self.owner.uid)

        os.mkdir(output_dir)

        input_file = PdfFileReader(file(filepath, 'rb'))

        for i in range(input_file.getNumPages()):
            with Image(filename = filepath + '[' + str(i) + ']', 
                resolution=100) as img:
                if len(size) > 0:
                    img.resize(width, height)

                img.format = format
                img.save(filename = output_dir + str(i) + '.' + format)

    def convert_to_png(self, width=0, height=0):
        self.__convert_to_img__(width, height, 'png')

    def convert_to_jpg(self, width=0, height=0):
        self.__convert_to_img__(width, height, 'jpg')

# --------------------------------------------------------------------

@receiver(models.signals.post_delete, sender=Document)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `Document` object is deleted.
    """
    if instance.docfile:
        if os.path.isfile(instance.docfile.path):
            os.remove(instance.docfile.path)

# --------------------------------------------------------------------

class Project_Log(models.Model):
    # Attributes
    message      = models.TextField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)
    semester   = models.CharField(max_length=50)
    start_sy   = models.CharField(max_length=50)
    end_sy     = models.CharField(max_length=50)

    # Relations
    project_log = models.ForeignKey(Project, related_name='project_log', null=True, blank=True)
    course_log = models.ForeignKey(Course_Faculty_Assignment, related_name='course_log', null = True, blank = True)
    actor   = models.ForeignKey(User, related_name='actor', null=True)

    # Methods
    def __unicode__(self):
        return self.message

# --------------------------------------------------------------------

class Project_Adviser_Request(models.Model):
    # Relations
    requester = models.ForeignKey(Project, related_name='requester')
    requested = models.ForeignKey(
        Course_Faculty_Assignment, related_name="requested",
    )
    accepted = models.NullBooleanField(null=True)

    def __unicode__(self):
        return self.requester.title

# --------------------------------------------------------------------

class User_Last_Visit_Ongoing(models.Model):
    # Attributes
    last_visit = models.DateTimeField(null=True)

    # Relations
    user = models.ForeignKey(User, related_name="user")

    def __unicode__(self):
        return str(self.last_visit)

# --------------------------------------------------------------------

class User_Docu_Request(models.Model):
    user = models.ForeignKey(User, related_name="docu_requester")
    req_docs = models.ForeignKey(Project, related_name='req_docs')
    semester   = models.CharField(max_length=50)
    start_sy   = models.CharField(max_length=50)
    end_sy     = models.CharField(max_length=50)
    access = models.NullBooleanField(null=False)

    def __unicode__(self):
        return str(self.user.username)

admin.site.register(Project)
admin.site.register(User_Docu_Request)
admin.site.register(Project_Membership)
admin.site.register(Event)
admin.site.register(Document)
admin.site.register(Project_Adviser_Request)

repository/templates/repository/partials/project_calendar.html
	
<div class="row">
	<div class="col-md-5">
		<br>
		<div class="alert alert-info">
			<ul>
				<li>Drag and drop events to transfer to another date and to shorten or elongate duration.</li>
				<li>Drag events to the trash icon to delete.</li>
				<li>You can only move/delete events that you posted.</li>
			</ul>
		</div>
		<h4>Deadlines</h4>
		<table class="table table-striped">
			<tbody>
				{% for deadline in deadlines %}
					<tr>
						<td>
							{% if deadline.posted_by == user %}
								<a id="{{ deadline.id }}" class="edit-event" href="#">
									<i class="fa fa-pencil blue-icon"></i>
								</a>
							{% endif %}

							{{ deadline.title }}
						</td>
						<td class="text-right">
							{{ deadline.start_date|date:"F d, o" }}
							{% if deadline.start_time %}
								|
								{{ deadline.start_time|date:"h:i a" }}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<h4>Journals</h4>
		<table class="table table-striped">
			<tbody>
				{% for journal in journals %}
					<tr>
						<td>
							{% if journal.posted_by == user %}
								<a id="{{ journal.id }}" class="edit-event" href="#">
									<i class="fa fa-pencil blue-icon"></i>
								</a>
							{% endif %}

							{{ journal.title }}
						</td>
						<td class="text-right">
							{{ journal.start_date|date:"F d, o" }}
							{% if journal.start_time %}
								|
								{{ journal.start_time|date:"h:i a" }}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col-md-7">
		<div class="text-right">
			<a href='#' type="button" class="btn btn-xs btn-default" data-toggle='modal' data-target='#journal-entry-modal'><i class='fa fa-calendar-o blue-icon'></i> Generate Journal</a>
		</div>
		<br>
		<div id="calendar-holder"></div>

	</div>
</div>

{% load staticfiles %}
<script src="{% static 'repository/js/calendar.js' %}"></script>
{% if project_status == "ongoing" %}
    <script src="{% static 'repository/js/calendar_control_button.js' %}"></script>
{% endif %}

repository/templates/repository/partials/project_files.html
	{# {% if project_status == "ongoing" %} #}
<!--     <a href="#" id="add-file">
    <i class="fa fa-plus blue-icon"></i>
    Add File 
</a>
<br> -->
<!--     <a href="#" data-toggle="modal" data-target="#journal-entry-modal" >
    <i class="fa fa-calendar-o blue-icon"></i>
    Generate Journal
</a>
<br> -->
	{# {% endif %} #}
<!--     <a href="{% url 'repository.views.view_documentation' project_status project.uid project.slug %}">
    <i class="fa fa-eye blue-icon"></i>
    View docu
</a> -->

<!-- <hr align="left"> -->

{% load prettytimes_tags %}

<div class="row">
    <div class="col-md-12">
        <div id="reached-cap-notification" style="display: none;" class="alert alert-danger clearfix" role="alert">
            <button type="button" class="close close-notif">×</button>
            <strong>Storage full!</strong>
            <span>Please remove unnecessary files</span>
        </div>

        <div id="insuff-space-notification" style="display: none;" class="alert alert-danger clearfix" role="alert">
            <button type="button" class="close close-notif">×</button>
            <strong>Insufficient space!</strong>
            <span>Please remove unnecessary files</span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="full-notification" style="display: none;" {% if reached_cap %}class="reached"{% endif %}>
            <i class="fa fa-exclamation-triangle blue-icon"></i>
            <span class="text-danger">Storage capacity is reached! Please remove unnecessary files</span>
        </div>

        <div class="progress">
            <div id="storage-gauge" class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: {{ percentage }}%">
            </div>
            <span class="progress-type"><span id="storage-gauge-label">{{ used_storage_size }}</span> mb of {{ capacity }} mb used ({{ free_size }} mb free)</span>
            <span id="storage-percentage" class="progress-completed">{{ percentage }}%</span>
        </div>

        <a href='#' type="button" class="btn btn-xs btn-default" id='add-file'><i class='fa fa-plus blue-icon'></i> Add File</a>
    </div>
</div>

<!-- {% if files %}
    {% for document in files %}
        <span>{{ document.filename }}</span>
        <a target="_blank" href="{% url 'repository.views.view_file' project_status project.uid project.slug document.id %}"><i class="fa fa-eye blue-icon"></i></a>
        <a href="{% url 'repository.views.download_file' project_status project.uid project.slug document.id %}"><i class="fa fa-download blue-icon"></i></a>
        <a href="{% url 'repository.views.delete_file' project_status project.uid project.slug document.id %}"><i class="fa fa-times blue-icon"></i></a>
        <br>
    {% endfor %}
{% else %}
    <p>No documents.</p>
{% endif %} -->

<div class="row">
    <div class="col-md-12">
            <div class="table-responsive">
                <table class="table tables-striped">
                    <thead>
                        <tr>
                            <th>Filename</th>
                            <th>Size</th>
                            <th>Uploader</th>
                            <th>Uploaded at (Date)</th>
                            <th>Uploaded at (Time)</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="files-container">
                        {% if files %}
                        {% for document in files %}
                            <tr id="file-{{ document.id }}">
                                <td>{{ document.filename }}</td>
                                <td>{{ document.docfile.size|filesizeformat }}</td>
                                <td>{{ document.uploaded_by.first_name }} {{ document.uploaded_by.last_name }}</td>
                                <td>{{ document.created_date|date:"F d, o" }}</td>
                                <td>{{ document.created_date|date:"h:i a" }}</td>
                                <td>
                                    <a class="btn btn-info btn-xs" target="_blank" href="{% url 'repository.views.view_file' project_status project.uid project.slug document.id %}">Open</a>
                                    <a class="btn btn-warning btn-xs" href="{% url 'repository.views.download_file' project_status project.uid project.slug document.id %}">Download</a>
                                    {% if document.uploaded_by == user or is_admin %}
                                    <a class="delete-file btn btn-danger btn-xs" href="{% url 'repository.views.delete_file' project_status project.uid project.slug document.id %}">Delete</a>                            
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                        <br>
                        <p id="no-doc">No documents</p>
                    {% endif %}
                </table>
            </div>
    </div>
</div>

<form class="hide" id="add-file-form" action="{% url 'repository.views.upload_file' project_status project.uid project.slug %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ add_file_form.non_field_errors }}</p>
    <p>{{ add_file_form.docfile.label_tag }}</p>
    <p>
        {{ add_file_form.docfile.errors }}
        {{ add_file_form.docfile }}
    </p>
    <p><input type="submit" value="Upload" /></p>
</form>

{% load staticfiles %}
<script src="{% static 'repository/js/files.js' %}"></script>
<script src="{% static 'repository/js/calendar.js' %}"></script>

repository/templates/repository/partials/project_log.html
{% load prettytimes_tags %}

<div id="log" class="row">
    <div class="col-md-12">
        <h4>Logs for {{ ssy }} - {{ esy }}, {{ sem }} term</h4>
        <table class="table tables-striped">
            <thead>
                <tr>
                    <th>Actor</th>
                    <th>Action</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th><i class="fa fa-clock-o"></i></th>
                </tr>
            </thead>
            <tbody>
                {% if logs %}
                    {% for log in logs %}
                        <tr>
                            <td>{{ log.actor.first_name }} {{ log.actor.last_name }}</td>
                            <td>{{ log.message|capfirst }}</td>
                            <td>{{ log.created_date|date:"F d, o" }}</td>
                            <td>{{ log.created_date|date:"h:i a" }}</td>
                            <td>{{ log.created_date|relative_time }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <p id="no-logs">No Logs</p>
                {% endif %}
            </tbody>
        </table>
        <!-- <ul class="list-group">
        {% if logs %}
            <p id="no-logs" style="display: none;">No documents</p>
            {% for log in logs %}
                <div class="list-group-item clearfix">
                    {{ log.actor.first_name }} {{ log.actor.last_name }} {{ log.message }}
                    <span id="file-control" class="pull-right">
                        {{ log.created_date|date:"F d, o (h:i a)" }}
                        ({{ log.created_date|relative_time }})
                    </span>
                </div>
            {% endfor %}
        {% else %}
            <p id="no-logs">No Logs</p>
        {% endif %}
        </ul> -->
    </div>
</div>

repository/templates/repository/partials/project_profile.html
{% include "repository/modals/add_member_modal.html" %}


<div id="profile" class="row">
    <div class="col-md-8">
        <span><strong>Abstract:</strong></span>
        {% if project.status != "published" %}
            {% if is_member %}
                <span style="display: none;" id="notifier"></span> <span id="chars-left" class="text-info" style="display: none;"> Character(s) left</span>
                <a href="#" id="edit-abstract">Edit <i class="fa fa-pencil-square-o blue-icon"></i></a>
            {% endif %}
        {% endif %}

        <p id="abstract">{{ project.abstract }}</p>

        {% if project.status != "published"  %}
            {% if is_member %}
                <form style="display: none;" id="edit-abstract-form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ abstract_form.abstract }}
                    </div>

                    <button type="submit" class="btn btn-default">Save</button>
                    <span id="abstract-error"></span>
                    
                </form>
            {% endif %}
        {% endif %}
    </div>
    <div class="col-md-4">
        <span><strong>Course: </strong>{{ project.coordinator.course }}</span>
        <br>
        <span><strong>Adviser: </strong>
        {% if project.status == "published" %}
            {{ adviser }}
        {% endif %}

        {% if project.status != "published" %}
            {% if adviser %}
                {{ adviser }}
            {% else %}
                {% if is_member == True %}
                    <a href="#" type="button" class="btn btn-xs btn-default" data-toggle="modal" data-target="#request-adviser-modal">
                        Request Adviser
                    </a>
                {% else %}
                    None
                {% endif %}
            {% endif %}
        {% endif %}
        </span>
        <br>
        <span><strong>Coordinator: </strong>{{ coordinator }}</span>
        <br>
        <span><strong>Created Date: </strong>{{ project.created_date|date:"F d, o" }}</span>
        <br>
        {% if project.status == "published" %}
        <span><strong>Published Date: </strong>{{ project.published_date|date:"F d, o" }}</span>
        {% endif %}

        {% if project_status == "ongoing" %}
            {% if request.user == project.coordinator.faculty or is_admin %}
                <span><strong>Project Code: </strong>{{ project.secret_code }}</span>
                <br>
            {% endif %}
        {% endif %}

        <hr align="left">    

        <span><strong>Members:</strong></span>
        {% if project.status == "ongoing" %}
            {% if is_coor or is_admin %}
                <br>
                <a href="#" type="button" class="btn btn-xs btn-default" data-toggle="modal" data-target="#add-member-modal">
                    <i class="fa fa-plus blue-icon"></i>
                    Add Member
                </a>
            {% endif %}
        {% endif %}
        <br>
        <div id="members">
        {% for member in members %}
            <span>{{ member.member.first_name }} {{ member.member.last_name }}</span>
            {% if project.status != "published" %}
                {% if request.user == member.member %}
                    <a id="{{ member.id }}" class="leave-group" title="Leave Group">
                        <span class="round-tabs one">
                            <i class="fa fa-times blue-icon"></i>
                        </span> 
                    </a>
                {% endif %}
                {% if is_coor or is_admin %}
                    <a id="{{ member.id }}" class="leave-group" title="Remove from project">
                        <span class="round-tabs one">
                            <i class="fa fa-times blue-icon"></i>
                        </span> 
                    </a>
                {% endif %}
            {% endif %}
            <br>
        {% endfor %}
        </div>
    </div>
</div>

<script>
    $(function(){
        $('a[title]').tooltip();

        $('.django-select2').djangoSelect2();
        
        $("#add-member-form").unbind().on('submit', function(e){
            e.preventDefault();
            var users = $("#add-member-form #id_user").val();
            addMembers(users);
        });

        $('#id_abstract').simplyCountable({
            counter:            '#notifier',
            countType:          'characters',
            maxCount:           5000,
            strictMax:          true,
            countDirection:     'down',
            safeClass:          'text-info',
            onOverCount:        function(count, countable, counter){},
            onSafeCount:        function(count, countable, counter){},
            onMaxCount:         function(count, countable, counter){}
        });
    })
</script>

repository/templates/repository/partials/search.html
{% if projects %}
	{% for project in projects %}
		<div class="col-md-4">
			<div 
				{% if project.status == 'ongoing' %}
					class='per badger-right badger-info' data-badger='ongoing'
				{% elif project.status == 'publication' %}
					class='per badger-right badger-success' data-badger='finalization'
				{% elif project.status == 'confirmation' %}
					class='per badger-right badger-danger' data-badger='confirmation'
				{% elif project.status == 'processing' %}
					class='per badger-right badger-warning' data-badger='processing'
				{% elif project.status == 'published' %}
					class='per'
				{% endif %}

				>

				<h4 class="per-title"><a class="project-titles" href="{% url 'repository.views.project_profile' project_status project.uid project.slug %}">{{ project.title }}</a></h4>
				<div class="per-desc">
					<p>{{ project.abstract }}</p>
				</div>
				<div class="tags">
					<span class="label label-info">{{ project.coordinator.course|title }}</span>
					{% if project_status == "ongoing" %}
						{% if project.coordinator.faculty == request.user %}
			                <span class="label label-default">Coordinator</span>
						{% endif %}

						{% if project.adviser.faculty == request.user %}
			                <span class="label label-default">Adviser</span>
						{% endif %}
					{% endif %}
				</div>
			</div>
		</div>
	{% endfor %}
{% else %}
	<div class="col-md-12">
		<h4>No Results Found</h4>
	</div>
{% endif %}